name: Validate Release Information

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  release-info:
    runs-on: ubuntu-latest
    env:
      PR_DESCRIPTION: ${{ github.event.pull_request.body }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $PR_DESCRIPTION
      - name: Set release type label
        run: |
          RELEASE_TYPES=$(echo "$PR_DESCRIPTION" | grep -oP '(?<=/release )\b(major|minor|patch|none)\b' || true)
          if [[ -z $RELEASE_TYPES ]]; then
            echo "No valid release type found. Specify /release <major|minor|patch|none> in the PR description."
            exit 1
          fi
          if [[ $(echo "$RELEASE_TYPES" | wc -l) -gt 1 ]]; then
            echo "Multiple release types found. Specify a single /release <major|minor|patch|none> in the PR description."
            exit 1
          fi
          RELEASE_LABEL="release/${RELEASE_TYPES}"
          OLD_LABEL=$(gh pr view ${{ github.event.number }} --json labels --jq '.labels[].name' | grep -E '^(release)/' || true)
          [[ $RELEASE_LABEL != $OLD_LABEL ]] && gh issue edit ${{ github.event.number }} --add-label "${RELEASE_LABEL}" --remove-label "${OLD_LABEL}"
          echo RELEASE_LABEL=$RELEASE_LABEL >> $GITHUB_ENV
      - name: Check release note
        run: |
          RELEASE_NOTE=$(echo "$PR_DESCRIPTION" | grep -Pzo '(?s)```release-note\n(.+)\n```' || true)
          RELEASE_NOTE_CONTENT=$(echo -e "$RELEASE_NOTE" | sed -n 2p)
          if [[ -z $RELEASE_NOTE ]]; then
            echo "No release note found. Please write a meaningful release note in the PR description in the format:"
            echo -e "```release-note\n<Description of the release>\n```"
            exit 1
          fi
          if [[ $RELEASE_NOTE_CONTENT == "None" && $RELEASE_LABEL != "release/none" ]]; then
            echo "Release note may not be 'NONE' since you specified release type $RELEASE_LABEL. Please write a meaningful release note."
            exit 1
          fi
